[package]
name = "proc-galaxy-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"
rand = "0.8.5"
more-asserts = "0.2.2"
float-cmp = "0.9.0"
base64 = "0.13.0"